version: '3'
services: 
    client: 
        build: 
            context: ./client
        ports: 
            - '3333:3000'
        environment: 
            - REACT_APP_API_URL=http://localhost:5001/api
        depends_on: 
            - server
        volumes:
            - ./client:/app/
            - /app/node_modules
        entrypoint: npm test -- --detectOpenHandles
    server: 
        build: 
            context: ./server
        environment: 
            - PGDATABASE=postgres
            - PGHOST=db
            - PGUSER=postgres
            - PGPASSWORD=password
            - PGPORT=5432
        entrypoint: npm test
        depends_on: 
            - db
        volumes: 
            - ./server:/app
            - /app/node_modules
    db: 
        build: 
            context: ./test-db
        volumes: 
            - db-test-volume:/var/lib/postgresql/data
volumes: 
    db-test-volume:
