version: '3'
services: 
    client: 
        build: 
            context: ./client
        ports: 
            - '3333:3000'
        environment: 
            - REACT_APP_API_URL=http://localhost:5001/api
        depends_on: 
            - server
        volumes:
            - ./client:/app/
            - /app/node_modules
    server: 
        build: 
            context: ./server
        ports: 
            - '5001:5000'
            - '9229:9229'
        environment: 
            - MONGODB_CONNSTRING=mongodb://db/messages
        depends_on: 
            - db
        volumes: 
            - ./server:/app
            - /app/node_modules
    db: 
        build: 
            context: ./db
        volumes: 
            - db-volume:/var/lib/mongo/data
        ports:
            - '27017:27017'
volumes: 
    db-volume:
